constants:
  swagger:
    info:
      title: SpringJPA
      description: 여러 가지 작업
      version: v0.1

spring:
  application:
    name: SpringJPA
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/spring_jpa
    username: root
    password: green502

springdoc:
  swagger-ui:
    default-models-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true